"""Initial migration

Revision ID: 512282d0e64e
Revises: 
Create Date: 2025-02-16 10:39:15.450530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '512282d0e64e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors',
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('doctor_id')
    )
    op.create_index(op.f('ix_doctors_doctor_id'), 'doctors', ['doctor_id'], unique=False)
    op.create_table('ingredients',
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('calories_per_100g', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('ingredient_id')
    )
    op.create_index(op.f('ix_ingredients_ingredient_id'), 'ingredients', ['ingredient_id'], unique=False)
    op.create_table('patients',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], ),
    sa.PrimaryKeyConstraint('patient_id')
    )
    op.create_index(op.f('ix_patients_patient_id'), 'patients', ['patient_id'], unique=False)
    op.create_table('goals',
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('date_start', sa.DateTime(), nullable=False),
    sa.Column('date_end', sa.DateTime(), nullable=False),
    sa.Column('calories_in_grams_per_day', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('goal_id')
    )
    op.create_index(op.f('ix_goals_goal_id'), 'goals', ['goal_id'], unique=False)
    op.create_table('meals',
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('date_start', sa.DateTime(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('meal_id')
    )
    op.create_index(op.f('ix_meals_meal_id'), 'meals', ['meal_id'], unique=False)
    op.create_table('detected_ingredients',
    sa.Column('detected_ingredient_id', sa.Integer(), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_name', sa.String(), nullable=False),
    sa.Column('quantity_grams', sa.Float(), nullable=False),
    sa.Column('calculated_calories', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.meal_id'], ),
    sa.PrimaryKeyConstraint('detected_ingredient_id')
    )
    op.create_index(op.f('ix_detected_ingredients_detected_ingredient_id'), 'detected_ingredients', ['detected_ingredient_id'], unique=False)
    op.create_table('modified_ingredients',
    sa.Column('modified_ingredient_id', sa.Integer(), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_name', sa.String(), nullable=False),
    sa.Column('detected_ingredient_id', sa.Integer(), nullable=True),
    sa.Column('quantity_grams', sa.Float(), nullable=False),
    sa.Column('calculated_calories', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['detected_ingredient_id'], ['detected_ingredients.detected_ingredient_id'], ),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.meal_id'], ),
    sa.PrimaryKeyConstraint('modified_ingredient_id')
    )
    op.create_index(op.f('ix_modified_ingredients_modified_ingredient_id'), 'modified_ingredients', ['modified_ingredient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_modified_ingredients_modified_ingredient_id'), table_name='modified_ingredients')
    op.drop_table('modified_ingredients')
    op.drop_index(op.f('ix_detected_ingredients_detected_ingredient_id'), table_name='detected_ingredients')
    op.drop_table('detected_ingredients')
    op.drop_index(op.f('ix_meals_meal_id'), table_name='meals')
    op.drop_table('meals')
    op.drop_index(op.f('ix_goals_goal_id'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_patients_patient_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_ingredients_ingredient_id'), table_name='ingredients')
    op.drop_table('ingredients')
    op.drop_index(op.f('ix_doctors_doctor_id'), table_name='doctors')
    op.drop_table('doctors')
    # ### end Alembic commands ###
