"""Initial migration

Revision ID: a2db1dae391a
Revises: 
Create Date: 2025-02-15 14:08:15.073934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2db1dae391a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foods',
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('calories_per_100g', sa.Float(), nullable=False),
    sa.Column('proteins_per_100g', sa.Float(), nullable=False),
    sa.Column('carbs_per_100g', sa.Float(), nullable=False),
    sa.Column('fats_per_100g', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('food_id')
    )
    op.create_index(op.f('ix_foods_food_id'), 'foods', ['food_id'], unique=False)
    op.create_table('meals',
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('total_calories', sa.Float(), nullable=True),
    sa.Column('total_proteins', sa.Float(), nullable=True),
    sa.Column('total_carbs', sa.Float(), nullable=True),
    sa.Column('total_fats', sa.Float(), nullable=True),
    sa.Column('meal_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('meal_id')
    )
    op.create_index(op.f('ix_meals_meal_id'), 'meals', ['meal_id'], unique=False)
    op.create_table('detected_foods',
    sa.Column('detected_food_id', sa.Integer(), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('estimated_weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.food_id'], ),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.meal_id'], ),
    sa.PrimaryKeyConstraint('detected_food_id')
    )
    op.create_index(op.f('ix_detected_foods_detected_food_id'), 'detected_foods', ['detected_food_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detected_foods_detected_food_id'), table_name='detected_foods')
    op.drop_table('detected_foods')
    op.drop_index(op.f('ix_meals_meal_id'), table_name='meals')
    op.drop_table('meals')
    op.drop_index(op.f('ix_foods_food_id'), table_name='foods')
    op.drop_table('foods')
    # ### end Alembic commands ###
